---
- name: Install wget
  yum: name=wget state=latest

- name : Download epel release
  shell: wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

#- name: Enable epel repo
#  shell: yum install epel-release-latest-7.noarch.rpm -y

- name: Installtion atop Redhat
  yum: name=atop state=latest
