---
- name: Install sysstat
  apt:
    name: sysstat
    state: latest
- name: Edit the configuration file
  lineinfile: dest=/etc/default/sysstat regexp=^ENABLED= line=ENABLED=true
- name: Service start
  service: name=sysstat state=started enabled=yes

