---
- name: Install sysstat
  apt:
    name: sysstat
    state: latest
- name: Edit the configuration file
  lineinfile: dest=/etc/default/sysstat regexp=^ENABLED= line=ENABLED=true
- name: Add cron entry for every two min
  lineinfile: dest=/etc/cron.d/sysstat line="*/2 * * * * root command -v debian-sa1 > /dev/null && debian-sa1 1 1"
- name: Service start
  service: name=sysstat state=started

